Makefile: added -Wno-unused-result to CFLAGS
Without this the build failed due to:

gz-sort.c: In function ‘first_pass’:
gz-sort.c:435:5: error: ignoring return value of ‘asprintf’, declared
with attribute warn_unused_result [-Werror=unused-result]
     asprintf(&report, "%s line count: %ld\n%s %s", misc->label,
in1.line_counter, misc->label, label2);